version: '3'
services:
  db:
    image: postgres:9.6-alpine
  web:
    build:
      context: .
      args:
        http_proxy: ${HTTP_PROXY}
        https_proxy: ${HTTP_PROXY}
        HTTP_PROXY: ${HTTP_PROXY}
        HTTPS_PROXY: ${HTTP_PROXY}
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    depends_on:
      - db
