#!/bin/sh
set -e
#set -o xtrace

function usage () {
    printf """
    DESCRIPTION:
        Create a new dockerized Phoenix project
    Example: ./init hello_world
    """

}

if  [[ -z  $1  ]]; then
  usage
  exit 1
fi

project_name=$1

#Build the image
docker build . -t ${project_name}:latest

function create_new_project() {
  #Create the project and get deps
  docker run -v `pwd`:/app ${project_name}:latest mix phoenix.new ${project_name}
  docker run -v `pwd`/${project_name}:/app ${project_name}:latest mix deps.get

  #Config the dev database
  sed -i.bak 's/hostname: "localhost"/hostname: "db"/g' ${project_name}/config/dev.exs
  rm -f ${project_name}/config/dev.exs.bak

  # Move everything to the root directory
  mv ${project_name}/* ./
  mv ${project_name}/.gitignore ./
  rm -rf ${project_name}

  #Set the image name in docker-compose
  sed -i.bak "s/replace_me_with_proper_image/${project_name}:latest/g" docker-compose.template
  mv docker-compose.template docker-compose.yml
  rm -r docker-compose.template.bak
}

if [ -f "docker-compose.template" ]; then
  echo "Initilizing ${project_name}"
  create_new_project
fi

#Start db and web components
docker-compose -p ${project_name} up -d
docker-compose -p ${project_name} run web mix ecto.create
docker-compose -p ${project_name} restart web
